/**
 * Ten letters a producer reads out.
 *   [TAKE-DESKTOP T-2; TAKE-PLATFORM P24; Doctrine D-25, D-03]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid or directly if it is a selfhost
 * > balancevid server, it can automatically connect"*
 *
 * THE DOOR IS CALLED, NOT READ. Whether a code is single-use
 * and whether it expires are facts about what happens when
 * somebody presents one twice, and a source-text test that the
 * record is deleted is satisfied by a version that deletes the
 * wrong file. This drives the real routes.
 */

import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import {
  PAIRING_ALPHABET, PAIRING_LENGTH, isPairingCode, readPairingCode,
  saysPairingCode,
} from '../../src/domain/pairing.js';

let root: string;
let mint: (r: Request, c: { params: Promise<{ requestId: string }> })
=> Promise<Response>;
let spend: (r: Request) => Promise<Response>;
let newRequest: typeof import('../../src/domain/participationEdit.js').newRequest;
let saveRequest: typeof import('../../src/store/requests.js').saveRequest;
let linkFor: typeof import('../../src/store/requests.js').linkFor;
let mintPairing: typeof import('../../src/store/pairings.js').mintPairing;
let spendPairing: typeof import('../../src/store/pairings.js').spendPairing;
let mutateRequest: typeof import('../../src/store/requests.js').mutateRequest;
/** A signed-in owner, as the middleware would have let through. */
let asOwnerCookie: string;

const AT = '2026-05-01T10:00:00.000Z';

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), 'bv-pair-'));
  process.env['BALANCEVID_VAR'] = root;
  process.env['BALANCEVID_PASSWORD'] = 'pairing-test-password';
  ({ newRequest } = await import('../../src/domain/participationEdit.js'));
  ({ saveRequest, linkFor, mutateRequest } =
    await import('../../src/store/requests.js'));
  const { AUTH } = await import('../../src/auth/config.js');
  const { issueSession, SESSION_COOKIE } =
    await import('../../src/auth/session.js');
  const { token } = await issueSession(AUTH.passwordHash!, 1);
  asOwnerCookie = `${SESSION_COOKIE}=${token}`;
  ({ mintPairing, spendPairing } = await import('../../src/store/pairings.js'));
  ({ POST: mint } = await import('../../app/api/requests/[requestId]/code/route.js'));
  ({ POST: spend } = await import('../../app/api/pair/route.js'));
});

afterAll(async () => {
  await rm(root, { recursive: true, force: true });
});

async function invited() {
  const request = newRequest({
    holder: { kind: 'channel', id: 'chan_pairing0000000001' },
    assignment: { kind: 'question', asks: 'Send in your service' },
    allowed: { video: true, takes: 3 },
    token: 'pairing-secret-token-1',
    now: AT,
  });
  await saveRequest(request);
  return request;
}

beforeEach(async () => {
  await rm(join(root, 'accounts'), { recursive: true, force: true });
});

describe('what a code is made of', () => {
  /*
   * THE ALPHABET LEAVES OUT WHAT PEOPLE MISREAD. Crockford's
   * set without I, L, O and U: no 0/O, no 1/l, and no
   * accidental words. A code somebody types wrong is a code
   * they type three times and then give up on. [U-19]
   */
  it('has no letter anybody confuses with another', () => {
    for (const letter of 'ILOU') {
      expect(PAIRING_ALPHABET.includes(letter), letter).toBe(false);
    }
    expect(PAIRING_ALPHABET).toHaveLength(32);
    expect(new Set(PAIRING_ALPHABET).size).toBe(32);
  });

  /*
   * TEN FROM THIRTY-TWO IS JUST OVER A THOUSAND BILLION. This
   * product has no rate limiter, which is the honest reason it
   * is ten and not six — six would be forty million and a
   * script.
   */
  it('is long enough to be worth guessing at', () => {
    expect(PAIRING_LENGTH).toBe(10);
    expect(PAIRING_ALPHABET.length ** PAIRING_LENGTH)
      .toBeGreaterThan(1e12);
  });

  /* Dashes, spaces and lower case all mean the same code. */
  it('reads what somebody typed, however they typed it', () => {
    expect(readPairingCode('K3M9P-TR2XW')).toBe('K3M9PTR2XW');
    expect(readPairingCode('k3m9p tr2xw')).toBe('K3M9PTR2XW');
    expect(readPairingCode('K3M9PTR2XW')).toBe('K3M9PTR2XW');
  });

  /*
   * AND IT DOES NOT GUESS. Turning `O` into `0` would be
   * guessing what somebody meant about a credential — the
   * alphabet was chosen so the pair is never both in it, which
   * makes the guess unnecessary as well as wrong.
   */
  it('refuses a letter that is not in the alphabet', () => {
    expect(readPairingCode('K3M9P-TR2XO')).toBeNull();
    expect(readPairingCode('IIIIIIIIII')).toBeNull();
    expect(readPairingCode('K3M9P-TR2X')).toBeNull();
    expect(readPairingCode('')).toBeNull();
    expect(isPairingCode('studio.example')).toBe(false);
  });

  /* Grouped for reading aloud; the door takes it either way. */
  it('is shown in fives', () => {
    expect(saysPairingCode('K3M9PTR2XW')).toBe('K3M9P-TR2XW');
    expect(readPairingCode(saysPairingCode('K3M9PTR2XW'))).toBe('K3M9PTR2XW');
  });
});

describe('minting and spending one', () => {
  const asOwner = (requestId: string) => mint(
    new Request(`http://local/api/requests/${requestId}/code`, {
      method: 'POST',
      headers: { cookie: asOwnerCookie },
    }),
    { params: Promise.resolve({ requestId }) });

  const present = (code: string) => spend(new Request('http://local/api/pair', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ code }),
  }));

  it('hands a station the link the code stood in for', async () => {
    const request = await invited();
    const said = await mintPairing(request.id, new Date().toISOString());
    const answer = await present(saysPairingCode(said.code));
    expect(answer.status).toBe(200);
    expect(((await answer.json()) as { link?: string }).link)
      .toBe(linkFor(request));
  });

  /*
   * ONCE, WHICH IS THE WHOLE OF ITS SAFETY. A code left on a
   * producer's screen after the station has used it is a
   * credential nobody can do anything with — which is the only
   * kind worth putting on a screen in a hall. [D-25]
   */
  it('is worth exactly one redemption', async () => {
    const request = await invited();
    const said = await mintPairing(request.id, new Date().toISOString());
    expect((await present(said.code)).status).toBe(200);
    expect((await present(said.code)).status).toBe(404);
  });

  /*
   * AND IT GOES COLD. Fifteen minutes is long enough to walk
   * across a hall and short enough that a code photographed
   * off a screen is worthless by the evening.
   */
  it('is nothing once it has expired', async () => {
    const request = await invited();
    const long = new Date(Date.now() - 60 * 60_000).toISOString();
    const said = await mintPairing(request.id, long);
    expect(await spendPairing(said.code, new Date().toISOString())).toBeNull();
  });

  /*
   * ONE ANSWER FOR EVERY REFUSAL. A door that could tell *that
   * code does not exist* from *that code has expired* is a
   * door somebody can use to learn which codes exist. [D-03]
   */
  it('answers alike whatever the reason', async () => {
    const request = await invited();
    const said = await mintPairing(request.id, new Date().toISOString());
    const never = (await present('K3M9PTR2XW')).status;
    const spent = (await (async () => {
      await present(said.code);
      return present(said.code);
    })()).status;
    const rubbish = (await present('not-a-code')).status;
    expect([never, spent, rubbish]).toEqual([404, 404, 404]);
  });

  /*
   * MINTING IS THE OWNER'S. The link is the credential and
   * this makes a stand-in for it; a route a stranger could
   * call would be a route that hands out invitations. [D-25]
   */
  it('is not minted by a stranger', async () => {
    const request = await invited();
    const answer = await mint(
      new Request(`http://local/api/requests/${request.id}/code`,
        { method: 'POST' }),
      { params: Promise.resolve({ requestId: request.id }) });
    expect(answer.status).toBe(404);
  });

  /* And the owner gets one, grouped for reading aloud. */
  it('is minted by the owner, in fives', async () => {
    const request = await invited();
    const answer = await asOwner(request.id);
    expect(answer.status).toBe(201);
    const said = await answer.json() as { code: string; expiresAt: string };
    expect(said.code).toMatch(/^[0-9A-HJKMNP-TV-Z]{5}-[0-9A-HJKMNP-TV-Z]{5}$/);
    expect(Date.parse(said.expiresAt)).toBeGreaterThan(Date.now());
    /* And it is a real one. */
    expect((await present(said.code)).status).toBe(200);
  });

  /*
   * A CODE FOR A REQUEST THAT HAS CLOSED SINCE IS NOTHING.
   * Fifteen minutes is long enough for a producer to change
   * their mind, and the check is the predicate the link itself
   * is judged by rather than a second opinion. [D-19]
   */
  it('is nothing once the producer has closed the request', async () => {
    const request = await invited();
    const said = await mintPairing(request.id, new Date().toISOString());
    /*
     * `attached` IS WHAT CLOSED MEANS HERE, by `isOpen` — the
     * predicate the link itself is judged by rather than a
     * second opinion about what closed means. [D-19]
     */
    await mutateRequest(request.id, (one) => {
      one.state = 'attached';
    });
    expect((await present(said.code)).status).toBe(404);
  });
});
