/**
 * Pairing codes — moved, not copied.
 *   [Doctrine D-19; TAKE-DESKTOP T-1, T-2]
 *
 * THIS FILE IS A DOOR, AND ITS CONTENTS ARE IN
 * `shared/src/pairing.ts`.
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid"*
 *
 * BOTH ENDS READ THE SAME TEN LETTERS. The installation mints
 * the code and prints it; the capture station recognises one in
 * its box and spends it. Two opinions about the alphabet, the
 * length or where the dash goes is a code a producer reads out
 * and an operator cannot type — and the one that was wrong
 * would be whichever end nobody tested with a person in the
 * room.
 */

export * from '../../shared/src/pairing.js';
