/**
 * Opening a room, and everything the host does in it.  [Doctrine ROOM §1–§8]
 *
 * Pure edits over the Conversation, in the same style as every other edit in
 * this product: a function that mutates a draft and throws `EditError` when
 * the change does not make sense. The API routes are thin wrappers, which is
 * what lets a test drive a whole seminar — open, invite, join, raise a hand,
 * bring someone in, send them back — without a browser.
 *
 * Nothing here knows about microphones, WebRTC or sockets. Who is speaking is
 * decided in `stage.ts` and who is allowed in is decided in `auth/guest.ts`;
 * this is the record of what was decided.
 */

import { EditError } from './edit.js';
import type { Conversation, Room } from './document.js';
import { newId } from './ids.js';
import {
  hostOf, inRoom, type Participant, type ParticipantId, type ParticipantRole,
} from './participants.js';

/**
 * Colours for the people in a room, in the order they arrive.  [U-20]
 *
 * Chosen to stay apart from each other and from the source's own blue, and to
 * remain distinguishable in greyscale by lightness as well as by hue — the
 * doctrine's rule is that identity never rests on colour alone, but colour
 * still has to do its share.
 */
export const PARTICIPANT_ACCENTS = [
  '#c2794f', '#4f8a5b', '#8a6fb0', '#c99a2e', '#3e7ca6', '#b5553f', '#5f8f8f',
];

/** How many people one room holds before it stops being a conversation. */
export const MAX_PARTICIPANTS = 50;

export interface OpenRoomOptions {
  /** The invite secret. Generated by the caller, which owns the CSPRNG. */
  inviteToken: string;
  hostName: string;
  now: string;
  speakerMode?: Room['speakerMode'];
}

/**
 * Open a room on a conversation.  [ROOM §6]
 *
 * The author becomes its host and its first participant — not a special case
 * beside the participant list, but the first entry in it, so every rule about
 * staging, naming and attribution applies to them as it does to everyone.
 */
export function openRoom(conversation: Conversation, options: OpenRoomOptions): Participant {
  if (conversation.room?.open) throw new EditError('this conversation already has a room');

  const participants = conversation.participants ?? [];
  let host = hostOf(participants);
  if (!host) {
    host = {
      id: newId('part') as ParticipantId,
      displayName: options.hostName.trim() || 'Host',
      role: 'host',
      accent: PARTICIPANT_ACCENTS[0]!,
      invitedAt: options.now,
      joinedAt: options.now,
    };
    participants.push(host);
  } else {
    // Re-opening: the host is here again, whatever happened last time.
    delete host.leftAt;
    host.joinedAt = host.joinedAt ?? options.now;
  }

  conversation.participants = participants;
  conversation.room = {
    inviteToken: options.inviteToken,
    issuedAt: options.now,
    open: true,
    speakerMode: options.speakerMode ?? 'automatic',
    stagedParticipantIds: [host.id],
  };
  return host;
}

/**
 * Close the room.
 *
 * Everyone's recordings stay, and so does everyone's name: the conversation
 * is made from them. What ends is the ability to join, and every guest
 * session with it — `callerFor` refuses a closed room whatever cookie it is
 * shown.
 */
export function closeRoom(conversation: Conversation, now: string): void {
  const room = requireRoom(conversation);
  room.open = false;
  for (const participant of conversation.participants ?? []) {
    if (inRoom(participant) && participant.role !== 'host') participant.leftAt = now;
  }
}

/**
 * Withdraw the invitation.  [ROOM §6]
 *
 * A new secret, which ends every guest session in this room — including
 * people already inside, because an invitation you cannot take back from the
 * people who used it is not one you can withdraw.
 */
export function rotateInvite(conversation: Conversation, inviteToken: string, now: string): void {
  const room = requireRoom(conversation);
  room.inviteToken = inviteToken;
  room.issuedAt = now;
}

/**
 * Someone follows the link and says who they are.  [ROOM §6, §12]
 *
 * A display name and nothing else: the brief is explicit that a participant
 * "doesn't necessarily need a Prof Class account". What comes back is a
 * participant record, which is what the guest session then names.
 */
export function joinRoom(
  conversation: Conversation, displayName: string, now: string,
  role: ParticipantRole = 'audience',
): Participant {
  const room = requireRoom(conversation);
  if (!room.open) throw new EditError('this room is closed');

  const name = displayName.trim();
  if (!name) throw new EditError('a name is needed, so people know who is speaking');
  if (name.length > 60) throw new EditError('that name is too long');

  const participants = conversation.participants ?? [];
  if (participants.filter(inRoom).length >= MAX_PARTICIPANTS) {
    throw new EditError('this room is full');
  }

  const participant: Participant = {
    id: newId('part') as ParticipantId,
    displayName: name,
    role,
    // Cycle the palette by arrival, so two people rarely share a colour and
    // nobody has to choose one before they can speak.
    accent: PARTICIPANT_ACCENTS[participants.length % PARTICIPANT_ACCENTS.length]!,
    invitedAt: now,
    joinedAt: now,
  };
  participants.push(participant);
  conversation.participants = participants;
  return participant;
}

/** They closed the tab, or the host removed them. Their recordings remain. */
export function leaveRoom(
  conversation: Conversation, participantId: string, now: string,
): void {
  const participant = requireParticipant(conversation, participantId);
  participant.leftAt = now;
  delete participant.handRaisedAt;
  const room = conversation.room;
  if (room?.stagedParticipantIds) {
    room.stagedParticipantIds = room.stagedParticipantIds.filter((id) => id !== participantId);
  }
}

/** Ask for the floor.  [ROOM §8] */
export function raiseHand(conversation: Conversation, participantId: string, now: string): void {
  const participant = requireParticipant(conversation, participantId);
  if (!inRoom(participant)) throw new EditError('they are not in the room');
  participant.handRaisedAt = now;
}

export function lowerHand(conversation: Conversation, participantId: string): void {
  delete requireParticipant(conversation, participantId).handRaisedAt;
}

/**
 * Put someone on stage, or take them off.  [ROOM §1, §4, §8]
 *
 * "Bring Sarah in" is this, and so is automatic switching landing on her:
 * §9's whole point is that the composition is told WHO and never how. Their
 * hand comes down when they are brought in, because it has been answered.
 */
export function setStaged(
  conversation: Conversation, participantIds: string[],
): void {
  const room = requireRoom(conversation);
  const staged: ParticipantId[] = [];
  for (const id of participantIds) {
    const participant = requireParticipant(conversation, id);
    if (!inRoom(participant)) throw new EditError(`${participant.displayName} is not in the room`);
    if (participant.role === 'audience') {
      /*
       * Bringing an audience member in promotes them, rather than being
       * refused. That IS the §8 move — the host decided they may speak, and
       * the role is the record of that decision rather than an obstacle to
       * it.
       */
      participant.role = 'speaker';
    }
    delete participant.handRaisedAt;
    if (!staged.includes(participant.id)) staged.push(participant.id);
  }
  room.stagedParticipantIds = staged;
}

/** How the stage is driven, and by whom.  [ROOM §3] */
export function setSpeakerMode(
  conversation: Conversation, mode: Room['speakerMode'],
): void {
  requireRoom(conversation).speakerMode = mode;
}

/** Pin someone, or release the pin.  [ROOM §3] */
export function setPinned(conversation: Conversation, participantId: string | null): void {
  const room = requireRoom(conversation);
  if (participantId === null) { delete room.pinnedParticipantId; return; }
  const participant = requireParticipant(conversation, participantId);
  if (!inRoom(participant)) throw new EditError('they are not in the room');
  room.pinnedParticipantId = participant.id;
}

function requireRoom(conversation: Conversation): Room {
  const room = conversation.room;
  if (!room) throw new EditError('this conversation has no room');
  return room;
}

function requireParticipant(conversation: Conversation, participantId: string): Participant {
  const participant = (conversation.participants ?? []).find((p) => p.id === participantId);
  if (!participant) throw new EditError('no such participant');
  return participant;
}
