/**
 * Minting and spending a pairing code.
 *   [TAKE-DESKTOP T-2; TAKE-PLATFORM P24; Doctrine D-25, D-03, U-06]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid"*
 *
 * ONE FILE PER CODE, NAMED BY THE CODE. The lookup goes from
 * the code to the request, because that is the direction a
 * station asks in: it holds ten letters somebody read off a
 * producer's screen and wants to know what they stand for. A
 * file per request would mean reading every request to answer
 * that. [paths.ts]
 *
 * SPENT ON READ, WHICH IS THE WHOLE OF ITS SAFETY. `spend`
 * deletes the file before it returns the link, so a code is
 * worth one redemption. A code left on a projector after the
 * station has used it is a credential nobody can do anything
 * with — which is the only kind of credential worth putting on
 * a projector. [D-25]
 *
 * AND EXPIRED ONES GO WHEN ANYTHING LOOKS. There is no sweeper
 * process in this product and a pairing code is a few hundred
 * bytes, so the cleanup rides on the read: anything stale found
 * while answering is removed. A deployment that never pairs
 * accumulates nothing, because nothing was ever minted.
 */

import { mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { randomInt } from 'node:crypto';

import {
  PAIRING_ALPHABET, PAIRING_LENGTH, type Pairing, pairingEnds, pairingSpent,
  readPairingCode,
} from '../domain/pairing.js';
import { paths } from './paths.js';

/**
 * A fresh code.
 *
 * `randomInt` AND NOT `Math.random`, because this is a
 * credential for a quarter of an hour and the difference
 * between the two is whether guessing the next one is
 * arithmetic. It draws uniformly from the alphabet with no
 * modulo bias, which is why it is one call per letter rather
 * than one call for a number. [D-25]
 */
export function newPairingCode(): string {
  let out = '';
  for (let at = 0; at < PAIRING_LENGTH; at += 1) {
    out += PAIRING_ALPHABET[randomInt(PAIRING_ALPHABET.length)];
  }
  return out;
}

/** Mint a code for this request. */
export async function mintPairing(
  requestId: string, now: string,
): Promise<Pairing> {
  const one: Pairing = {
    code: newPairingCode(),
    requestId,
    madeAt: now,
    expiresAt: pairingEnds(now),
  };
  const target = paths.pairing(one.code);
  await mkdir(paths.pairings(), { recursive: true });
  /*
   * WRITTEN TO A TEMPORARY NAME AND RENAMED, so a station that
   * redeemed a code mid-write could never read half a record
   * and conclude the code was for request `req_abc` when it was
   * for `req_abcdef`.
   */
  const temp = `${target}.${process.pid}.tmp`;
  await writeFile(temp, JSON.stringify(one, null, 2), 'utf8');
  await rename(temp, target);
  return one;
}

/**
 * Spend a code, or answer nothing.
 *
 * NOTHING FOR EVERY WAY OF FAILING — not a code, no such code,
 * expired, unreadable. A station that could tell *that code
 * does not exist* from *that code has expired* would be a
 * station somebody could use to find out which codes exist.
 * [D-03]
 */
export async function spendPairing(
  said: string, now: string,
): Promise<Pairing | null> {
  void sweepPairings(now);
  const code = readPairingCode(said);
  if (!code) return null;
  const target = paths.pairing(code);
  let one: Pairing;
  try {
    one = JSON.parse(await readFile(target, 'utf8')) as Pairing;
  } catch {
    return null;
  }
  /*
   * DELETED BEFORE IT IS JUDGED, which is deliberate: a code
   * that was presented is a code that is used up, whether or
   * not it turned out to be in time. Two stations racing on one
   * code both get one answer between them, and the loser gets
   * nothing rather than a second chance.
   */
  await rm(target, { force: true }).catch(() => undefined);
  if (pairingSpent(one, now)) return null;
  if (typeof one.requestId !== 'string' || one.requestId === '') return null;
  return one;
}

/**
 * Everything stale, removed.
 *
 * NOT AWAITED BY THE CALLER, because a station waiting to
 * connect should not wait on housekeeping for codes that are
 * nothing to do with it. A failure here is no failure at all:
 * the records it did not remove are already worthless and will
 * be swept next time. [U-19]
 */
export async function sweepPairings(now: string): Promise<void> {
  let held: string[];
  try {
    held = await readdir(paths.pairings());
  } catch {
    return;
  }
  await Promise.all(held.map(async (name) => {
    if (!name.endsWith('.json')) return;
    const at = `${paths.pairings()}/${name}`;
    try {
      const one = JSON.parse(await readFile(at, 'utf8')) as Pairing;
      if (pairingSpent(one, now)) await rm(at, { force: true });
    } catch {
      await rm(at, { force: true }).catch(() => undefined);
    }
  }));
}
