/**
 * Transcript persistence.  [Doctrine U-03, U-05, U-25]
 *
 * Transcripts are VERSIONED and a re-transcription never destroys the prior
 * version, because interventions are anchored to it (U-05). An anchor that
 * cannot be re-located against a newer transcript must still be able to look
 * at the one it was made against.
 */

import { mkdir, readFile, readdir, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Transcript } from '../transcribe/types.js';
import { paths, safe } from './paths.js';

function dir(conversationId: string): string {
  return join(paths.conversation(conversationId), 'transcript');
}

export async function saveTranscript(
  conversationId: string, transcript: Transcript,
): Promise<number> {
  await mkdir(dir(conversationId), { recursive: true });
  const version = (await listTranscriptVersions(conversationId)).at(-1) ?? 0;
  const next = version + 1;
  const target = join(dir(conversationId), `v${next}.json`);
  const temp = `${target}.${process.pid}.tmp`;
  await writeFile(temp, JSON.stringify(transcript, null, 2), 'utf8');
  await rename(temp, target);
  return next;
}

export async function listTranscriptVersions(conversationId: string): Promise<number[]> {
  try {
    const names = await readdir(dir(safe(conversationId)));
    return names
      .map((n) => /^v(\d+)\.json$/.exec(n)?.[1])
      .filter((n): n is string => Boolean(n))
      .map(Number)
      .sort((a, b) => a - b);
  } catch {
    return [];
  }
}

export async function loadTranscript(
  conversationId: string, version?: number,
): Promise<{ version: number; transcript: Transcript } | null> {
  const versions = await listTranscriptVersions(conversationId);
  const wanted = version ?? versions.at(-1);
  if (!wanted || !versions.includes(wanted)) return null;
  const raw = await readFile(join(dir(safe(conversationId)), `v${wanted}.json`), 'utf8');
  return { version: wanted, transcript: JSON.parse(raw) as Transcript };
}

/**
 * Take transcripts.  [Doctrine U-19 §4]
 *
 * "Response captions are generated by transcribing the user's own take."
 * Stored per take rather than per conversation, because a take is replaceable
 * and re-recording must not invalidate the source transcript.
 */
export async function saveTakeTranscript(
  conversationId: string, takeId: string, transcript: Transcript,
): Promise<void> {
  const target = join(dir(conversationId), 'takes');
  await mkdir(target, { recursive: true });
  const file = join(target, `${safe(takeId)}.json`);
  const temp = `${file}.${process.pid}.tmp`;
  await writeFile(temp, JSON.stringify(transcript, null, 2), 'utf8');
  await rename(temp, file);
}

export async function loadTakeTranscript(
  conversationId: string, takeId: string,
): Promise<Transcript | null> {
  try {
    const raw = await readFile(join(dir(safe(conversationId)), 'takes', `${safe(takeId)}.json`), 'utf8');
    return JSON.parse(raw) as Transcript;
  } catch {
    return null;
  }
}

export async function loadAllTakeTranscripts(
  conversationId: string,
): Promise<Map<string, Transcript>> {
  const out = new Map<string, Transcript>();
  try {
    const takesDir = join(dir(safe(conversationId)), 'takes');
    for (const name of await readdir(takesDir)) {
      if (!name.endsWith('.json')) continue;
      const takeId = name.replace(/\.json$/, '');
      const raw = await readFile(join(takesDir, name), 'utf8');
      out.set(takeId, JSON.parse(raw) as Transcript);
    }
  } catch { /* none yet */ }
  return out;
}
