import { isOpen } from '../../../src/domain/participation.js';
import { linkFor, loadRequest } from '../../../src/store/requests.js';
import { spendPairing } from '../../../src/store/pairings.js';
import { fail, json } from '../../../src/web/http.js';

export const dynamic = 'force-dynamic';

/**
 * Spending a pairing code.  [TAKE-DESKTOP T-2; D-25, D-03]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid"*
 *
 * PUBLIC, BECAUSE THE THING PRESENTING IT HAS NO ACCOUNT. A
 * capture station in a hall is not signed in to anything and
 * never will be — the whole protocol is that a link is a
 * credential and the holder of one is who they are. This takes
 * a shorter credential and hands back the long one. [D-25]
 *
 * ONE ANSWER FOR EVERY REFUSAL. Not a code, no such code,
 * expired, already spent, or a request that has closed since —
 * all of them answer the same way, because a door that could
 * tell them apart is a door somebody can use to learn which
 * codes exist. [D-03]
 *
 * A POST FOR SOMETHING THAT READS, WHICH IS NOT A MISTAKE.
 * Spending a code CHANGES it: the record is deleted before the
 * link is returned, so this is not idempotent and must not be
 * put in a URL, a log line or a browser's history. The same
 * reasoning the claim routes apply to minting a request.
 */
export async function POST(request: Request): Promise<Response> {
  const no = () => fail(404, 'that code is no good');

  let said: { code?: unknown };
  try {
    said = await request.json() as { code?: unknown };
  } catch {
    return no();
  }
  if (typeof said.code !== 'string') return no();

  const now = new Date().toISOString();
  const spent = await spendPairing(said.code, now);
  if (!spent) return no();

  let found;
  try {
    found = await loadRequest(spent.requestId);
  } catch {
    return no();
  }
  /*
   * CHECKED AGAIN AT THE DOOR, because fifteen minutes is long
   * enough for a producer to change their mind. The code was
   * minted against an open request; what matters is whether it
   * is open now. [D-19]
   */
  if (!isOpen(found, now)) return no();

  return json({ link: linkFor(found) });
}
