import { isOwner } from '../../../../../src/auth/request.js';
import { isOpen } from '../../../../../src/domain/participation.js';
import { PAIRING_LIFE_MS, saysPairingCode } from '../../../../../src/domain/pairing.js';
import { loadRequest } from '../../../../../src/store/requests.js';
import { mintPairing } from '../../../../../src/store/pairings.js';
import { fail, json } from '../../../../../src/web/http.js';

export const dynamic = 'force-dynamic';

type Params = { params: Promise<{ requestId: string }> };

/** The shape our ids have. Refused rather than sanitised. [INV-15] */
const REQUEST = /^req_[A-Za-z0-9]{1,64}$/;

/**
 * A code a capture station can be typed into.
 *   [TAKE-DESKTOP T-2; TAKE-PLATFORM P24; D-25, D-03]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid"*
 *
 * THE LINK IS SIXTY-FOUR CHARACTERS AND THE TWO MACHINES ARE
 * NOT CONNECTED. A producer's laptop has the invitation; the
 * capture station at the front of the hall has four cameras and
 * a keyboard. Everything between them is a person reading one
 * screen and typing into the other, and `req_<20>.<43>` is not
 * a thing anybody types correctly.
 *
 * SO THE STATION IS TOLD TEN LETTERS AND SPENDS THEM. The code
 * stands in for the link for a quarter of an hour and once;
 * what comes back at `/api/pair` is the link itself, and the
 * code is gone. It is not a second credential with a second
 * lifetime. [pairing.ts]
 *
 * OWNER-ONLY, LIKE THE SQUARE BESIDE IT. The link is the
 * credential and this mints a stand-in for it, so a route a
 * stranger could call would be a route that hands out
 * invitations. [D-25]
 *
 * AND A CLOSED REQUEST HAS NO CODE, by the predicate the link
 * itself is judged by rather than a second opinion about what
 * closed means. A code read out to a hall that answers *that
 * link is not open* is worse than no code: the operator types
 * it three times and blames the station. [D-19]
 */
export async function POST(request: Request, { params }: Params): Promise<Response> {
  const { requestId } = await params;
  if (!REQUEST.test(requestId)) return fail(404, 'no such request');
  if (!(await isOwner(request))) return fail(404, 'no such request');

  let found;
  try {
    found = await loadRequest(requestId);
  } catch {
    return fail(404, 'no such request');
  }
  const now = new Date().toISOString();
  if (!isOpen(found, now)) return fail(409, 'that request is closed');

  const made = await mintPairing(found.id, now);
  return json({
    /* Grouped for reading aloud; the door takes it either way. */
    code: saysPairingCode(made.code),
    expiresAt: made.expiresAt,
    lifeMs: PAIRING_LIFE_MS,
  }, { status: 201 });
}
