/**
 * Finding a BalanceVid on this machine.
 *   [TAKE-DESKTOP T-2; TAKE-PLATFORM P24; Doctrine D-19, U-19]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid or directly if it is a selfhost
 * > balancevid server, it can automatically connect"*
 *
 * A SELF-HOSTED INSTALLATION IS USUALLY ON THE SAME MACHINE AS
 * THE STATION, and the operator was being asked to type its
 * address anyway. That is a question the program can answer for
 * itself: there are four places a BalanceVid listens on a
 * laptop, and asking all four costs four requests that fail in
 * milliseconds when nothing is there.
 *
 * LOOPBACK ONLY, AND THAT IS THE WHOLE OF ITS SAFETY. This
 * never scans a network. A capture station that swept the
 * subnet for things answering `/api/participate` would be a
 * program doing something nobody asked it to on somebody
 * else's wifi — and the hall it is standing in is as likely to
 * be a school's as a studio's. `localhost` and `127.0.0.1` are
 * this computer, which is the only computer whose owner is
 * also the person holding the laptop. [T-2]
 *
 * IT OFFERS AND NEVER CHOOSES. What *automatically connect*
 * means here is that the address is already filled in and named
 * — not that the station silently points four cameras at
 * whatever answered. An operator presses it. [D-21]
 *
 * THE PORTS ARE THE ONES THIS PRODUCT ACTUALLY USES. 3000 is
 * what the Dockerfile sets and what `next start` defaults to;
 * 3001 is what a second instance on one machine lands on. A
 * longer list would be a port scan of a loopback interface,
 * which is still a port scan.
 */

import { askInstance } from './ask.js';
import type { Instance } from '../../shared/src/connections.js';

/** Where a BalanceVid on this computer answers. */
export const NEARBY = [
  'http://localhost:3000',
  'http://127.0.0.1:3000',
  'http://localhost:3001',
  'http://127.0.0.1:3001',
] as const;

/**
 * HOW LONG ONE OF THEM HAS.
 *
 * Much shorter than `ASK_TIMEOUT_MS`, because this is four
 * speculative requests to a machine that is answering from its
 * own memory or not at all. A connection refused comes back at
 * once; anything that takes a second and a half on loopback is
 * not a BalanceVid waking up, it is something else listening on
 * that port.
 */
export const NEARBY_TIMEOUT_MS = 1_500;

export interface Found {
  origin: string;
  instance: Instance;
}

/**
 * Whatever is listening on this computer.
 *
 * ALL FOUR AT ONCE, because they are independent and the slow
 * one is the one that is not there. In order of the list rather
 * than of who answered first, so the same machine offers the
 * same thing twice running — a list that reordered itself
 * between two openings of the same screen is a list an operator
 * stops trusting.
 *
 * ONE PER INSTALLATION, AND *THE SAME INSTALLATION* IS A
 * HARDER QUESTION THAN IT LOOKS.
 *
 * `localhost:3000` and `127.0.0.1:3000` are the same server
 * answering twice, and offering both would be asking somebody
 * to choose between two spellings of one thing. The obvious key
 * is the instance's own origin — and `instanceFrom` sets that
 * to the origin we REACHED rather than the one the body claims,
 * deliberately, so it is the same two spellings again.
 *
 * SO IT IS THE PORT AND THE NAME. One process binds one port on
 * one host, so two loopback addresses answering alike on 3000
 * are one server — except that `localhost` can resolve to `::1`
 * where `127.0.0.1` is the v4 stack, and two different servers
 * COULD sit on the two. Vanishingly rare, and the name is what
 * tells them apart when it happens: same port and same name is
 * one row, different names are two. Nothing is hidden that is
 * actually different. [U-19]
 *
 * AND `localhost` WINS THE SPELLING, because it is the one
 * somebody would have typed.
 */
export async function nearby(
  where: readonly string[] = NEARBY,
  timeoutMs = NEARBY_TIMEOUT_MS,
): Promise<Found[]> {
  const answers = await Promise.all(where.map(async (origin) => {
    const asked = await askInstance(origin, timeoutMs).catch(() => null);
    return asked ? { origin, instance: asked.instance } : null;
  }));
  const seen = new Set<string>();
  const out: Found[] = [];
  for (const one of answers) {
    if (!one) continue;
    const key = `${portOf(one.origin)}\u0000${one.instance.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(one);
  }
  return out;
}

/** The port, or nothing — which is still a usable key. */
function portOf(origin: string): string {
  try {
    const url = new URL(origin);
    return url.port || (url.protocol === 'https:' ? '443' : '80');
  } catch {
    return origin;
  }
}
