/**
 * Spending a code a producer read out.
 *   [TAKE-DESKTOP T-2; TAKE-PLATFORM P24; Doctrine D-25, U-19]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid"*
 *
 * THE LINK IS SIXTY-FOUR CHARACTERS AND THE TWO MACHINES ARE
 * NOT CONNECTED TO EACH OTHER. A producer's laptop has the
 * invitation; the capture station at the front of the hall has
 * four cameras and a keyboard, and everything between them is a
 * person reading one screen and typing into the other.
 * `req_<20>.<43>` is not a thing anybody types correctly, and
 * ten letters from an alphabet with no `O` and no `1` is.
 *
 * ONE REQUEST, AND IT IS A POST. Spending a code destroys it:
 * the installation deletes the record before it answers, so
 * this is never retried blindly — a second attempt with the
 * same code is a second attempt at nothing. That is also why
 * the code is safe to leave on a producer's screen after the
 * station has used it.
 *
 * AND IT ENDS WHERE `askInstance` ENDS: in the main process,
 * over `fetch`, with no credentials and a timeout. The window's
 * policy is still `connect-src 'none'`.
 */

import { asOrigin } from '../../shared/src/connections.js';
import { readPairingCode } from '../../shared/src/pairing.js';
import { askInstance } from './ask.js';
import { type Destination } from './submit.js';
import { writeCall } from './store.js';

/** How long the installation has to answer ten letters. */
export const PAIR_TIMEOUT_MS = 10_000;

/**
 * Spend a code at an installation, and point the station at
 * what it turns out to be.
 *
 * THE NAME COMES FROM THE INSTALLATION, NOT FROM THE CODE. A
 * code says nothing about whose studio it is, and an operator
 * about to send a service somewhere needs to read the name of
 * the place it is going. So the instance is asked as well —
 * one extra request, on a screen somebody is standing at.
 * [D-21]
 *
 * NOTHING FOR EVERY WAY OF FAILING: not a code, not an origin,
 * unreachable, refused, or an answer that is not a link. A
 * station that could tell *that code is wrong* from *that
 * studio is asleep* would be a station somebody could use to
 * find out which codes exist on an installation they cannot
 * otherwise see. The screen says one thing and the operator
 * does the same thing about all of them: check the code, check
 * the address, try again. [D-03, U-19]
 */
export async function pairWith(
  typed: string, said: string, timeoutMs = PAIR_TIMEOUT_MS,
): Promise<Destination | null> {
  const origin = asOrigin(typed);
  const code = readPairingCode(said);
  if (!origin || !code) return null;

  const halt = new AbortController();
  const timer = setTimeout(() => halt.abort(), timeoutMs);
  let link: string;
  try {
    const answer = await fetch(`${origin}/api/pair`, {
      method: 'POST',
      credentials: 'omit',
      cache: 'no-store',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ code }),
      signal: halt.signal,
    });
    if (!answer.ok) return null;
    const body = await answer.json() as { link?: unknown };
    if (typeof body.link !== 'string' || body.link === '') return null;
    link = body.link;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }

  /*
   * THE NAME, SO THE OPERATOR CAN READ WHERE IT IS GOING. A
   * studio that will not say what it is called is still a
   * studio, and refusing the pairing over a missing name
   * would throw away a credential that has already been
   * spent. The origin is the fallback, which is what the
   * CONNECT screen already does for an installation with no
   * name. [U-19]
   */
  const asked = await askInstance(origin, timeoutMs).catch(() => null);
  return writeCall({
    origin: asked?.instance.origin ?? origin,
    link,
    name: asked?.instance.name || origin,
  });
}
