/**
 * A code somebody reads off one screen and types into another.
 *   [TAKE-DESKTOP T-2; TAKE-PLATFORM P24; Doctrine D-25, D-03]
 *
 * > *"it can be connected to the balancevid through Code
 * > generated by balancevid or directly if it is a selfhost
 * > balancevid server, it can automatically connect"*
 *
 * THE LINK IS SIXTY-FOUR CHARACTERS AND A CAPTURE STATION HAS
 * NO CLIPBOARD FROM THE STUDIO. `req_<20>.<43>` goes through a
 * message perfectly and is unusable when the only route between
 * the two machines is a person looking at one and typing into
 * the other — which is exactly the situation in a hall, where
 * the laptop with the cameras on it is not the laptop with the
 * producer's email open.
 *
 * SO THE STUDIO MINTS A SHORT ONE AND THE STATION SPENDS IT.
 * The code is not a second credential with a second lifetime:
 * it stands in for the link for a quarter of an hour and once,
 * and what comes back is the link itself. After that the code
 * is nothing. [D-25]
 *
 * TEN CHARACTERS FROM THIRTY-TWO, which is just over a thousand
 * billion. A guess has a quarter of an hour and one try per
 * code to find one of however many are open on an installation
 * — and this product has no rate limiter, which is the honest
 * reason it is ten and not six. Six would be forty million and
 * a script.
 *
 * AND THE ALPHABET LEAVES OUT WHAT PEOPLE MISREAD. Crockford's
 * set without `I`, `L`, `O` and `U`: no `0`/`O`, no `1`/`l`, and
 * no accidental words. A code somebody types wrong is a code
 * they type three times and then give up on. [U-19]
 *
 * Nothing here touches the filesystem, the network or a clock.
 */

/** The letters a pairing code is made of. */
export const PAIRING_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

export const PAIRING_LENGTH = 10;

/** How long a code stands in for a link. */
export const PAIRING_LIFE_MS = 15 * 60 * 1000;

/**
 * A code, as it is shown.
 *
 * GROUPED IN FIVES, because a person reads a code off one
 * screen and types it into another and ten undifferentiated
 * characters is where they lose their place. The groups are
 * presentation: `readPairingCode` takes them back out, so what
 * somebody types with or without the dash is the same code.
 */
export function saysPairingCode(code: string): string {
  const clean = code.toUpperCase();
  return `${clean.slice(0, 5)}-${clean.slice(5)}`;
}

/**
 * What somebody typed, as a code or as nothing.
 *
 * FORGIVING ABOUT EVERYTHING EXCEPT THE LETTERS. Dashes,
 * spaces and lower case all arrive and all mean the same code;
 * a character that is not in the alphabet does not, because the
 * alphabet was chosen so that the ones people confuse are not
 * both in it. Turning `O` into `0` would be guessing what
 * somebody meant about a credential. [U-19]
 */
export function readPairingCode(said: string): string | null {
  const clean = said.toUpperCase().replace(/[\s-]+/g, '');
  if (clean.length !== PAIRING_LENGTH) return null;
  for (const letter of clean) {
    if (!PAIRING_ALPHABET.includes(letter)) return null;
  }
  return clean;
}

/**
 * Whether a string could be a code at all.
 *
 * USED BY THE STATION'S BOX, which has to tell an address from
 * a link from a code before it knows where to send any of
 * them. A thing that is not a code is a thing that might be an
 * address, which is why this answers rather than refusing.
 */
export function isPairingCode(said: string): boolean {
  return readPairingCode(said) !== null;
}

/** A minted code, as it is stored. */
export interface Pairing {
  code: string;
  /** The request it stands in for. */
  requestId: string;
  madeAt: string;
  expiresAt: string;
}

/**
 * Whether this code is still worth anything.
 *
 * COMPARED AS INSTANTS, so a clock in another timezone cannot
 * make a code live longer there than here. The same reasoning
 * `takingEntries` applies to a campaign's window.
 */
export function pairingSpent(one: Pairing, now: string): boolean {
  const ends = Date.parse(one.expiresAt);
  if (!Number.isFinite(ends)) return true;
  return Date.parse(now) >= ends;
}

/** When a code minted now runs out. */
export function pairingEnds(now: string, lifeMs = PAIRING_LIFE_MS): string {
  return new Date(Date.parse(now) + lifeMs).toISOString();
}

/**
 * How long is left, for the screen showing it.
 *
 * A CODE WITHOUT A CLOCK BESIDE IT IS A CODE SOMEBODY READS
 * OUT TWENTY MINUTES LATER and then blames the station for. The
 * producer is the one who can see both screens; they are the
 * one who has to know it is going cold. [D-21]
 */
export function pairingLeftMs(one: Pairing, now: string): number {
  return Math.max(0, Date.parse(one.expiresAt) - Date.parse(now));
}
