/**
 * What a link to a conversation says about itself.  [Doctrine U-31, D-03]
 *
 * One place, used by both surfaces a link can point at — the watch page and
 * the article — so the two cannot describe the same conversation differently.
 * The card's words are decided by `buildShareCard`; this only works out where
 * the pictures and pages live and whether this caller is allowed to be told
 * any of it.
 */
import { stat } from 'node:fs/promises';

import { isPubliclyVisible } from '../auth/policy.js';
import type { Conversation } from '../domain/document.js';
import { buildAttribution } from '../domain/plan.js';
import { projectTimeline } from '../domain/timeline.js';
import { buildShareCard, type ShareCard } from '../publish/card.js';
import { paths } from '../store/paths.js';

export interface Share {
  card: ShareCard;
  pageUrl: string;
  /**
   * Absent when the picture has not been drawn.
   *
   * The worker draws it beside the thumbnails, so anything published since
   * this shipped has one — but a conversation published before it does not,
   * and claiming an image that answers 404 is a small lie the page does not
   * need to tell. The words still travel; only the picture is missing.
   */
  imageUrl?: string;
}

/**
 * Absolute, because a preview is resolved by a machine that has no page to
 * resolve a relative URL against.
 *
 * Behind a proxy the request's own URL is the internal one, so the forwarded
 * headers win where they exist. An instance reached over plain HTTP in
 * development still produces a URL that works there.
 */
export function originOf(request: Request): string {
  const headers = request.headers;
  const host = headers.get('x-forwarded-host') ?? headers.get('host');
  if (!host) return new URL(request.url).origin;
  const proto = headers.get('x-forwarded-proto')
    ?? (host.startsWith('localhost') || host.startsWith('127.0.0.1') ? 'http' : 'https');
  return `${proto}://${host}`;
}

/**
 * The card for this conversation, or nothing.
 *
 * Nothing for a draft, and that is the point rather than an omission: a
 * preview is generated by whatever the link was pasted into, so metadata on an
 * unpublished conversation would hand the author's title and their unfinished
 * argument to any machine that fetched the URL. The existence of a draft is
 * private (D-03), and a page with no card simply has nothing to say.
 *
 * The question is whether the CONVERSATION is published, not who is asking.
 * An author looking at their own published page should see what everyone else
 * sees; a draft has no preview for anybody, its author included, because
 * there is nothing published to preview.
 */
export async function shareFor(
  request: Request, conversation: Conversation, page: 'watch' | 'article',
): Promise<Share | undefined> {
  if (!isPubliclyVisible(conversation)) return undefined;

  const drawn = await stat(paths.shareCard(conversation.id))
    .then((file) => file.size > 0).catch(() => false);

  let totalOutputFrames: number | undefined;
  try { totalOutputFrames = projectTimeline(conversation).totalOutputFrames; }
  catch { totalOutputFrames = undefined; }

  const origin = originOf(request);
  return {
    card: buildShareCard({
      conversation,
      attribution: buildAttribution(conversation, conversation.createdAt).text,
      ...(totalOutputFrames ? { totalOutputFrames } : {}),
    }),
    pageUrl: `${origin}/c/${conversation.id}/${page}`,
    ...(drawn ? { imageUrl: `${origin}/api/conversations/${conversation.id}/card` } : {}),
  };
}
